Repository git3080ti/Invaders, pull requests merged in 2020-12, with the labels that each got.

#19 Update config.yml include filter & mvn
  .circleci/config.yml
Labels: Maintenance

#18 Add pom.xml
  pom.xml
Labels: Maintenance

#20 Update pom.xml change version name #14
  pom.xml
Labels: Maintenance

#17 #7 에 대한 기능 추가
  src/engine/DrawManager.java
  src/screen/GameScreen.java
Labels: Game Design, UI/UX, enhancement

#13 Feature/reset scores
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .idea/Invaders.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  src/engine/Core.java
  src/engine/DrawManager.java
  src/engine/FileManager.java
  src/graphics
  src/scores
  src/screen/ResetScoreScreen.java
  src/screen/TitleScreen.java
Labels: Design, Game Design, enhancement

#23 Add Difficulty System
  src/engine/Core.java
  src/engine/DrawManager.java
  src/screen/DifficultyScreen.java
Labels: Game Design, Modes, UI/UX, enhancement

#24 fix Bug #22
  src/engine/DrawManager.java
  src/screen/ResetScoreScreen.java
Labels: bug

#26 Create ShipTest.java
  test/entity/ShipTest.java
Labels: Maintenance

#35 change project for junit test #25
  .circleci/config.yml
  .gitignore
  .idea/Invaders.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  pom.xml
  src/main/java/engine/Cooldown.java
  src/main/java/engine/Core.java
  src/main/java/engine/DrawManager.java
  src/main/java/engine/FileManager.java
  src/main/java/engine/Frame.java
  src/main/java/engine/GameSettings.java
  src/main/java/engine/GameState.java
  src/main/java/engine/InputManager.java
  src/main/java/engine/MinimalFormatter.java
  src/main/java/engine/Score.java
  src/main/java/entity/Bullet.java
  src/main/java/entity/BulletPool.java
  src/main/java/entity/EnemyShip.java
  src/main/java/entity/EnemyShipFormation.java
  src/main/java/entity/Entity.java
  src/main/java/entity/Ship.java
  src/main/java/screen/DifficultyScreen.java
  src/main/java/screen/GameScreen.java
  src/main/java/screen/HighScoreScreen.java
  src/main/java/screen/ResetScoreScreen.java
  src/main/java/screen/ScoreScreen.java
  src/main/java/screen/Screen.java
  src/main/java/screen/TitleScreen.java
  src/test/java/entity/ShipTest.java
Labels: Maintenance, feature

#36 change pom, replace data files
  pom.xml
  src/main/java/graphics
  src/main/java/scores
Labels: bug

#38 maven 버전 수정
  .circleci/config.yml
  pom.xml
Labels: bug

#39 Update ShipTest.java
  src/test/java/entity/ShipTest.java
Labels: bug
